# Generated by Django 4.2.2 on 2023-07-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, unique=True, verbose_name='RUC')),
                ('social_reason', models.CharField(max_length=50, verbose_name='Razón Social')),
                ('commercial_name', models.CharField(max_length=50, verbose_name='Nombre Comercial')),
                ('main_address', models.CharField(max_length=50, verbose_name='Dirección Matriz')),
                ('stablishement_address', models.CharField(max_length=50, verbose_name='Dirección Establecimiento')),
                ('stablishement_code', models.CharField(max_length=3, verbose_name='Código Establecimiento')),
                ('emition_point_code', models.CharField(max_length=3, verbose_name='Código Punto de Emisión')),
                ('contability_obligation', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], max_length=2, verbose_name='Obligado a llevar contabilidad')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d')),
                ('enviroment', models.CharField(choices=[('PRODUCCION', 'PRODUCCION'), ('PRUEBAS', 'PRUEBAS')], max_length=10, verbose_name='Entorno')),
            ],
            options={
                'verbose_name': 'Entidad',
                'verbose_name_plural': 'Entidades',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='iva',
            field=models.CharField(choices=[('0.00', '0.00'), ('12.00', '12.00')], default='0.00', max_length=5),
        ),
    ]
