# Generated by Django 4.2.2 on 2023-07-13 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_remove_sale_iva_product_sale_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saledetails',
            name='subtotal',
        ),
    ]
