# Generated by Django 4.2.2 on 2023-07-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_saledetails_subtotal_alter_saledetails_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetails',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
