# Generated by Django 4.2.2 on 2023-07-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_alter_client_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_type',
            field=models.CharField(choices=[('Cedula', 'Cédula'), ('RUC', 'RUC'), ('Pasaporte', 'Pasaporte')], default='Cedula', max_length=10, verbose_name='Tipo de Identificación'),
        ),
    ]
