# Generated by Django 4.2.2 on 2023-07-16 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_client_id_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Cédula, RUC o Pasaporte'),
        ),
    ]
